version: "2.1"

services:
  plex-api:
    build:
      context: ./yt-get
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: npm run start:prod
    environment:
      - REDIS__HOST=localhost
      - REDIS__PORT=6420
      - PORT=3820
    ports:
      - 3820:3820

  redis: # To be used in plex-api by bull queue
    image: redis
    ports:
      - '6420:6379'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - cache:/data

  # samba:
  #   image: dperson/samba # no tags, only latest
  #   restart: always
  #   command: '-u "ubuntu_msi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - TZ=America/Lima
  #   ports:
  #     - 139:139
  #     - 445:445
  #   volumes:
  #     - ${MEDIA}:/media
  #     - ${STORAGE}/torrents:/downloads

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Lima
  #     - VERSION=docker
  #     - PLEX_CLAIM=claim-2rPx9CMGJ9dF2mxs-sv7
  #   volumes:
  #     - ${MEDIA}:/media
  #     - ${STORAGE}/config:/config
  #     - ${STORAGE}/tmp:/tmp
  #   restart: unless-stopped

volumes:
  cache: