version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - VERSION=docker
      - PLEX_CLAIM=claim-2rPx9CMGJ9dF2mxs-sv7
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/config:/config
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped

